# Generated by Django 6.0.3 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_followuprecord_doctor_delete_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="followuprecord",
            name="ai_generated",
            field=models.BooleanField(default=False, verbose_name="是否AI自动随访"),
        ),
        migrations.AddField(
            model_name="followuprecord",
            name="decision_reason",
            field=models.TextField(blank=True, verbose_name="继续跟进判断理由"),
        ),
        migrations.AddField(
            model_name="followuprecord",
            name="need_further_followup",
            field=models.BooleanField(default=True, verbose_name="是否需继续跟进"),
        ),
        migrations.AddField(
            model_name="patient",
            name="contact_method",
            field=models.CharField(
                choices=[("phone", "电话"), ("sms", "短信"), ("wechat", "微信")],
                default="phone",
                max_length=20,
                verbose_name="随访方式",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="followup_status",
            field=models.CharField(
                choices=[
                    ("pending", "待随访"),
                    ("completed", "已完成"),
                    ("no_needed", "无需继续"),
                ],
                default="pending",
                max_length=20,
                verbose_name="随访状态",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="next_follow_up_date",
            field=models.DateField(blank=True, null=True, verbose_name="下次随访日期"),
        ),
    ]
